#!/bin/bash
# script migrated to stat1005

ulimit -v 400000

set -e 
set -o pipefail

wikistats=$WIKISTATS_SCRIPTS
analytics=$wikistats/analytics
perl=$wikistats/analytics/perl

wikistats_data=$WIKISTATS_DATA
csv_out=$wikistats_data/analytics/csv 
csv_dumps=$wikistats_data/dumps/csv 
# unmerged=-u # uncomment to use legacy method of counting editors (unmerged, excluding commons)

clear

# Prepare several csv files, ready for importing into analytics database / front-end (e.g. LIMN)
# All generated files have _in_ in name signalling these contain data ready for importing into database / front-end

# www.walkernews.net/2007/06/03/date-arithmetic-in-linux-shell-scripts
# yyyymm=$(date -d "1 month ago" +"%Y-%m")
# yyyymm2=$(date -d "2 month ago" +"%Y-%m")
# yyyymm=2012-08 # !!!!!!  yyyymm "1 month ago" on 31 July gives 2012-07 !!!1 
# hard coded until auto set is more robust (day 21-31 use previous month, day 1-20 use two months ago)
yyyymm=2018-04 # last month to report on  
yyyymm2=2018-03 # previous month for comto compare 
yyyymm_rc=2018-05 # rc is month of RC meeting # no longer used in meeting

log=$wikistats_data/analytics/logs/prep_csv_$yyyymm.log 

set -x # show commands

mkdir -p $csv_out/$yyyymm

cd $perl

# AnalyticsPrepBinariesData.pl read counts for binaries which were generated by wikistats 
# and which reside in /a/wikistats/csv_[project code]/StatisticsPerBinariesExtension.csv
# It filters and reorganizes data and produces analytics_in_binaries.csv
# Output csv contains: project code, language, month, extension name, count

# might be reactivated, not needed for current question
# perl AnalyticsPrepBinariesData.pl -i $csv_dumps -o $csv_out/$yyyymm | tee $log | cat

# AnalyticsPrepWikiCountsOutput.pl reads a plethora of fields from several csv files from wikistats process
# - It filters and reorganizes data and produces analytics_in_wikistats.csv, ready for import 

perl AnalyticsPrepWikiCountsOutputMisc.pl -i $csv_dumps -o $csv_out/$yyyymm -m $yyyymm           | tee -a $log | cat
perl AnalyticsPrepWikiCountsOutputCore.pl -i $csv_dumps -o $csv_out/$yyyymm -m $yyyymm $unmerged | tee -a $log | cat

# analytics_in_page_views.csv is written daily as part of WikiCountsSummarizeProjectCounts.pl 
# part of (/home/ezachte/wikistats/projectviews_monthly.sh job) (monthly refers to output granularity)
# which processes hourly projectviews files (per wiki page view totals for one hour) from https://dumps.wikimedia.org/other/pageviews/
# and generates several files on different aggregation levels
# only action here is to copy data to this folder to have everything in one place
# note: unlike folder name suggests this file contains stats for all projects
# for overview see https://wikitech.wikimedia.org/w/images/8/8d/Monthly_Pageview_Reports.png

# might be reactivated, not needed for current question
# cp /a/dammit.lt/projectviews/csv/csv_wp/analytics_in_page_views.csv $csv_out/$yyyymm 
# cp /a/dammit.lt/projectviews/csv/csv_wp/wikilytics_in_pageviews.csv $csv_out/$yyyymm 

echo -e "\n>>> ready <<<"
